name: Assert flow message

on: [pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        flow-version: [0.110.0, 0.111.3, 0.112.0, 0.113.0, 0.114.0, 0.115.0, 0.116.1, 0.117.0]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn bootstrap
    - run: yarn build
    - run: yarn add -DW flow-bin@${{ matrix.flow-version }}
    - run: yarn lerna run --scope flow-type-tests test
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: flow-error-message-fixtures
        path: packages/flow-type-tests/__tests__/fixtures
